branches:
  only:
    - master

environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\build.cmd"

  matrix:

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "SET NUMBA_ENABLE_CUDASIM=1"
  - "%CMD_IN_ENV% python -m pip install -U pip setuptools wheel"
  - "%CMD_IN_ENV% python -m pip install -r requirements.txt"
  - "%CMD_IN_ENV% python -m pip install -e ."

build: off

test_script:
  - "%CMD_IN_ENV% python -m pytest -vv --ignore=src --pyargs skallel_tensor"
